[target.aarch64-apple-darwin]
linker = "zig"
rustflags = [
    "-C", "link-arg=cc",
    "-C", "link-arg=-target",
    "-C", "link-arg=aarch64-macos",
    "-C", "link-arg=--sysroot=C:/Users/debas/Documents/oxidedb/oxidedb/sdk",
]

[target.x86_64-apple-darwin]
linker = "zig"
rustflags = [
    "-C", "link-arg=cc",
    "-C", "link-arg=-target",
    "-C", "link-arg=x86_64-macos",
    "-C", "link-arg=--sysroot=C:/Users/debas/Documents/oxidedb/oxidedb/sdk",
]
